name: tokumemo_plus
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  dio: ^5.3.2 #TODO:API用
  retrofit: ^4.0.1 #TODO:APIのGETのリクエストをおこなう
  flutter_riverpod: ^2.3.7 #TODO:状態管理
  webview_flutter: ^4.2.2 #TODO:webページを開く
  carousel_slider: ^4.2.1 #TODO:ホーム画面のカルーセル表示
  logger: ^2.0.1 #TODO:ロギングの設定を行う
  flutter_secure_storage: ^8.0.0 #TODO:（個人情報）情報を内部に保存
  shared_preferences: ^2.2.0 #TODO:情報を内部に保存

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.2
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  flutter_native_splash: ^2.3.2 #TODO:スプラッシュ画面の構築

flutter_native_splash:
  color: '#add8e6'
  image: 'assets/images/tokumemoIcon/tokumemoIcon/icon.png'
  color_dark: '#262626'
  image_dark: 'assets/images/tokumemoIcon/tokumemoIcon/icon.png'
  fullscreen: true
  android13:
    icon_background_color: '#add8e6'
    image: 'assets/images/tokumemoIcon/tokumemoIcon/icon.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/images/tokumemoIcon/tokumemoIcon/icon.png'

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
    - assets/images/tokumemoIcon/tokumemoIcon/Android
    - assets/images/tokumemoIcon/tokumemoIcon/memokichi
    - assets/images/tokumemoIcon/tokumemoIcon/menuIcon
    - assets/images/tokumemoIcon/tokumemoIcon/tabIcon
    - assets/images/tokumemoIcon/tokumemoIcon/icon.png


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
